export { default as Hero } from './Hero.js'
export { default as Features } from './Features.js'
export { default as About } from './About.js'
export { default as Testimonials } from './Testimonials.js'
export { default as Pricing } from './Pricing.js'
export { default as Contact } from './Contact.js'